		include "src/game/common/durezas_check_01.inc";
        
        //***************************************************************
        //***************************************************************
        
		include "src/game/common/durezas_check_02.inc";
        
        //***************************************************************
        //***************************************************************
        
		include "src/game/common/durezas_check_03.inc";
        
		//*********************************************************
        //  comprobación tile actual
        //*********************************************************
        
		include "src/game/common/durezas_check_04.inc";
		
		//include "src/game/common/durezas_check_test.inc";